In [1]:
import pandas as pd 
import numpy as np

In [2]:
def shrink(x,alpha):
    return np.sign(x)*np.max(np.abs(x)-alpha,0)

In [86]:
def ISTA(D,x,alpha, lamb):
    D= np.array(D)
    h = np.zeros([np.shape(D)[1],1])
    converged = False
    while not converged:
        h_prime = h
        h = h - np.dot(alpha*D.T,np.dot(D,h)-x)
        h = shrink(h,alpha*lamb)
        print(h)
        if np.linalg.norm(h-h_prime) < 0.01:
            converged = True 
    return h

In [87]:
A = [[ 1.,  0.],
       [ 1.,  1.],
       [ 0.,  1.]]

K = [[ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]]
W = np.dot(K,A)
y = np.array([[1],[1],[3],[2]])

In [88]:
W

array([[ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  1.],
       [ 0.,  1.]])

In [89]:
ISTA(W,y,0.5,0.5)

[[ 2.25]
 [ 2.25]]
[[ 1.125]
 [ 1.125]]
[[ 1.6875]
 [ 1.6875]]
[[ 1.40625]
 [ 1.40625]]
[[ 1.546875]
 [ 1.546875]]
[[ 1.4765625]
 [ 1.4765625]]
[[ 1.51171875]
 [ 1.51171875]]
[[ 1.49414062]
 [ 1.49414062]]
[[ 1.50292969]
 [ 1.50292969]]
[[ 1.49853516]
 [ 1.49853516]]


array([[ 1.49853516],
       [ 1.49853516]])

In [73]:
D= np.array(W)
h = np.zeros([np.shape(D)[1],1])

In [74]:
np.shape(D)[1]

2

In [75]:
h_prime = h
boom= np.dot(D,h)

In [76]:
np.shape(boom)

(4, 1)

In [77]:
D

array([[ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  1.],
       [ 0.,  1.]])

In [78]:
np.shape(D)[1]

2

In [79]:
y

array([[1],
       [1],
       [3],
       [2]])

In [80]:
np.shape(0.5*D.T)

(2, 4)

In [81]:
np.shape(boom)

(4, 1)

In [84]:
np.shape(np.dot(D,h)-y)

(4, 1)

In [85]:
h = h - np.dot(0.5*D.T,np.dot(D,h)-y)