In [115]:
import pandas as pd 
import numpy as np

In [116]:
def shrink(x,alpha):
    return np.sign(x)*np.max(np.abs(x)-alpha,0)

In [121]:
def ISTA(D,x,alpha, lamb, treshold):
    critical_value = max(np.linalg.eigvals(np.dot(D.T,D)))
    if (alpha*critical_value > 1):
        raise ValueError('Your alpha is too big.')
        
    D= np.array(D)
    h = np.zeros([np.shape(D)[1],1])
    converged = False
    while not converged:
        h_prime = h
        h = h - np.dot(alpha*D.T,np.dot(D,h)-x)
        h = shrink(h,alpha*lamb)
        if np.linalg.norm(h-h_prime) < treshold:
            converged = True 
    return h

In [122]:
A = [[ 1.,  0.],
       [ 1.,  1.],
       [ 0.,  1.]]

K = [[ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]]
W = np.dot(K,A)
y = np.array([[1],[1],[3],[2]])

In [123]:
W

array([[ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  1.],
       [ 0.,  1.]])

In [126]:
ISTA(W,y,0.1,0,0.01)

array([[ 1.6505185],
       [ 1.6505185]])

In [108]:
D= np.array(W)
h = np.zeros([np.shape(D)[1],1])

In [74]:
np.shape(D)[1]

2

In [109]:
h_prime = h
boom= np.dot(D,h)

In [76]:
np.shape(boom)

(4, 1)

In [77]:
D

array([[ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  1.],
       [ 0.,  1.]])

In [78]:
np.shape(D)[1]

2

In [79]:
y

array([[1],
       [1],
       [3],
       [2]])

In [80]:
np.shape(0.5*D.T)

(2, 4)

In [81]:
np.shape(boom)

(4, 1)

In [84]:
np.shape(np.dot(D,h)-y)

(4, 1)

In [85]:
h = h - np.dot(0.5*D.T,np.dot(D,h)-y)

In [111]:
critical_value = 0.5*max(np.linalg.eigvals(np.dot(D.T,D)))

In [112]:
critical_value

1.8090169943749475